import {
  DoorOpen,
  Fence,
  Grid2X2,
  Home,
  Layers3,
  Paintbrush,
  PanelTop,
  RectangleHorizontal,
  Rows3,
  Sparkles,
  SquareStack,
  StepForward,
  Triangle,
  Wrench
} from "lucide-react";

const PASCAL_ICON_BASE = "/assets/pascal-icons";

export const STUDIO_CATALOG_CATEGORIES = [
  { id: "roof", label: "지붕", icon: Triangle, iconSrc: `${PASCAL_ICON_BASE}/roof.webp` },
  { id: "roof-decor", label: "지붕 장식", icon: Sparkles, iconSrc: `${PASCAL_ICON_BASE}/roof.webp` },
  { id: "roof-pattern", label: "지붕 패턴", icon: Paintbrush, iconSrc: `${PASCAL_ICON_BASE}/paint.webp` },
  { id: "roof-trim", label: "지붕 테두리", icon: PanelTop, iconSrc: `${PASCAL_ICON_BASE}/roof.webp` },
  { id: "exterior-trim", label: "프리즈/외부 테두리", icon: RectangleHorizontal, iconSrc: `${PASCAL_ICON_BASE}/wall.webp` },
  { id: "wall-tool", label: "벽 도구", icon: SquareStack, iconSrc: `${PASCAL_ICON_BASE}/wall.webp` },
  { id: "door", label: "문", icon: DoorOpen, iconSrc: `${PASCAL_ICON_BASE}/door.webp` },
  { id: "window", label: "창문", icon: Grid2X2, iconSrc: `${PASCAL_ICON_BASE}/window.webp` },
  { id: "wall-pattern", label: "벽 패턴", icon: Paintbrush, iconSrc: `${PASCAL_ICON_BASE}/paint.webp` },
  { id: "spandrel", label: "스팬드럴", icon: Rows3, iconSrc: `${PASCAL_ICON_BASE}/wallcut.webp` },
  { id: "column", label: "기둥", icon: Layers3, iconSrc: `${PASCAL_ICON_BASE}/column.webp` },
  { id: "gate", label: "게이트", icon: Fence, iconSrc: `${PASCAL_ICON_BASE}/fence.webp` },
  { id: "stairs-ladder", label: "계단/사다리", icon: StepForward, iconSrc: `${PASCAL_ICON_BASE}/stairs.webp` },
  { id: "railing", label: "계단 난간", icon: Wrench, iconSrc: `${PASCAL_ICON_BASE}/fence.webp` }
];

export const STUDIO_CATALOG_ASSETS = [
  { id: "test-roof-gable", categoryId: "roof", label: "박공지붕", shape: "gable", placementMode: "roof-attached", size: [2, 1, 1], color: "#d2ad75" },
  { id: "test-roof-hip", categoryId: "roof", label: "경사지붕", shape: "hip", placementMode: "roof-attached", size: [2, 1, 1], color: "#cda66f" },
  { id: "test-roof-flat", categoryId: "roof", label: "평지붕", shape: "slab", placementMode: "roof-attached", size: [2, 0.35, 1], color: "#8fb4d7" },
  { id: "test-roof-shed", categoryId: "roof", label: "외쪽지붕", shape: "shed", placementMode: "roof-attached", size: [2, 0.75, 1], color: "#c0a06c" },
  { id: "test-roof-decor-01", categoryId: "roof-decor", label: "지붕 박공 장식", shape: "trim", placementMode: "roof-accessory", size: [1, 0.35, 0.35], color: "#e0cfad" },
  { id: "test-roof-decor-dormer", categoryId: "roof-decor", label: "도머 장식", shape: "gable", placementMode: "roof-accessory", size: [0.9, 0.55, 0.55], color: "#d7c49a", previewMaterialLabel: "dormer" },
  { id: "test-roof-decor-chimney", categoryId: "roof-decor", label: "굴뚝 장식", shape: "box", placementMode: "roof-accessory", size: [0.38, 0.85, 0.38], color: "#a87963", previewMaterialLabel: "chimney" },
  { id: "test-roof-pattern-01", categoryId: "roof-pattern", label: "기와 패턴", shape: "tile", placementMode: "roof-accessory", size: [1, 0.18, 1], color: "#6f8791" },
  { id: "test-roof-pattern-standing-seam", categoryId: "roof-pattern", label: "세로 금속 지붕", shape: "tile", placementMode: "roof-accessory", size: [1, 0.12, 1], color: "#8a979d", previewMaterialLabel: "seam" },
  { id: "test-roof-pattern-slate", categoryId: "roof-pattern", label: "슬레이트 패턴", shape: "tile", placementMode: "roof-accessory", size: [1, 0.14, 1], color: "#64707a", previewMaterialLabel: "slate" },
  { id: "test-roof-trim-01", categoryId: "roof-trim", label: "처마 테두리", shape: "beam", placementMode: "roof-accessory", size: [2, 0.2, 0.2], color: "#6f5c49" },
  { id: "test-roof-trim-fascia", categoryId: "roof-trim", label: "두꺼운 파시아", shape: "beam", placementMode: "roof-accessory", size: [2.2, 0.28, 0.18], color: "#594a3c", previewMaterialLabel: "fascia" },
  { id: "test-roof-trim-slim-eave", categoryId: "roof-trim", label: "슬림 처마선", shape: "beam", placementMode: "roof-accessory", size: [2.1, 0.12, 0.16], color: "#8a755e", previewMaterialLabel: "eave" },
  {
    id: "test-exterior-trim-01",
    categoryId: "exterior-trim",
    label: "외부 몰딩",
    shape: "beam",
    placementMode: "wall-attached",
    attachmentSize: [2, 0.22],
    attachDepth: 0.08,
    size: [2, 0.2, 0.2],
    color: "#f0eadf"
  },
  {
    id: "test-exterior-trim-frieze-band",
    categoryId: "exterior-trim",
    label: "프리즈 밴드",
    shape: "beam",
    placementMode: "wall-attached",
    attachmentSize: [2.4, 0.18],
    attachDepth: 0.07,
    size: [2.4, 0.18, 0.14],
    color: "#e6ddcf",
    previewMaterialLabel: "frieze"
  },
  {
    id: "test-exterior-trim-corner-board",
    categoryId: "exterior-trim",
    label: "코너 보드",
    shape: "beam",
    placementMode: "wall-attached",
    attachmentSize: [0.22, 2.4],
    attachDepth: 0.09,
    size: [0.22, 2.4, 0.14],
    color: "#f5f0e6",
    previewMaterialLabel: "corner"
  },
  {
    id: "test-wall-line",
    categoryId: "wall-tool",
    label: "직선 벽",
    shape: "wall-line",
    placementMode: "draw-wall",
    drawMode: "chain-wall",
    supportKind: "wall",
    size: [1, 2.7, 0.16],
    wallHeight: 2.7,
    wallThickness: 0.16,
    color: "#7fb6a8"
  },
  {
    id: "test-wall-partition-90",
    categoryId: "wall-tool",
    label: "내부 파티션 90",
    shape: "wall-line",
    placementMode: "draw-wall",
    drawMode: "chain-wall",
    supportKind: "wall",
    size: [1, 2.7, 0.09],
    wallHeight: 2.7,
    wallThickness: 0.09,
    color: "#9fc9bd",
    previewMaterialLabel: "90mm"
  },
  {
    id: "test-wall-partition-120",
    categoryId: "wall-tool",
    label: "내부 파티션 120",
    shape: "wall-line",
    placementMode: "draw-wall",
    drawMode: "chain-wall",
    supportKind: "wall",
    size: [1, 2.7, 0.12],
    wallHeight: 2.7,
    wallThickness: 0.12,
    color: "#93c1b5",
    previewMaterialLabel: "120mm"
  },
  {
    id: "test-wall-cube",
    categoryId: "wall-tool",
    label: "1m 벽 블록",
    shape: "box",
    placementMode: "floor-structural",
    supportKind: "wall",
    size: [1, 2.7, 0.16],
    color: "#7fb6a8"
  },
  {
    id: "test-wall-room",
    categoryId: "wall-tool",
    label: "직사각형 방",
    shape: "room",
    placementMode: "draw-room",
    size: [2, 2.7, 2],
    wallHeight: 2.7,
    wallThickness: 0.16,
    color: "#a9c9bd"
  },
  {
    id: "test-wall-half",
    categoryId: "wall-tool",
    label: "반벽",
    shape: "wall-line",
    placementMode: "draw-wall",
    drawMode: "chain-wall",
    supportKind: "wall",
    size: [1, 1.2, 0.16],
    wallHeight: 1.2,
    wallThickness: 0.16,
    color: "#9fc1b7",
    previewMaterialLabel: "half"
  },
  {
    id: "test-wall-low-600",
    categoryId: "wall-tool",
    label: "낮은 벽 600",
    shape: "wall-line",
    placementMode: "draw-wall",
    drawMode: "chain-wall",
    supportKind: "wall",
    size: [1, 0.6, 0.14],
    wallHeight: 0.6,
    wallThickness: 0.14,
    color: "#b0cec5",
    previewMaterialLabel: "600"
  },
  {
    id: "test-wall-low-1200",
    categoryId: "wall-tool",
    label: "낮은 벽 1200",
    shape: "wall-line",
    placementMode: "draw-wall",
    drawMode: "chain-wall",
    supportKind: "wall",
    size: [1, 1.2, 0.18],
    wallHeight: 1.2,
    wallThickness: 0.18,
    color: "#98bfb5",
    previewMaterialLabel: "1200"
  },
  {
    id: "test-wall-thick-exterior",
    categoryId: "wall-tool",
    label: "외벽 라인",
    shape: "wall-line",
    placementMode: "draw-wall",
    drawMode: "chain-wall",
    supportKind: "wall",
    size: [1, 2.7, 0.24],
    wallHeight: 2.7,
    wallThickness: 0.24,
    color: "#78aa9f",
    previewMaterialLabel: "exterior"
  },
  {
    id: "test-wall-exterior-200",
    categoryId: "wall-tool",
    label: "외벽 200",
    shape: "wall-line",
    placementMode: "draw-wall",
    drawMode: "chain-wall",
    supportKind: "wall",
    size: [1, 2.7, 0.2],
    wallHeight: 2.7,
    wallThickness: 0.2,
    color: "#83b1a5",
    previewMaterialLabel: "200mm"
  },
  {
    id: "test-wall-thick-300",
    categoryId: "wall-tool",
    label: "두꺼운 벽 300",
    shape: "wall-line",
    placementMode: "draw-wall",
    drawMode: "chain-wall",
    supportKind: "wall",
    size: [1, 2.7, 0.3],
    wallHeight: 2.7,
    wallThickness: 0.3,
    color: "#7aa99d",
    previewMaterialLabel: "300mm"
  },
  {
    id: "test-wall-thick-450",
    categoryId: "wall-tool",
    label: "두꺼운 벽 450",
    shape: "wall-line",
    placementMode: "draw-wall",
    drawMode: "chain-wall",
    supportKind: "wall",
    size: [1, 2.7, 0.45],
    wallHeight: 2.7,
    wallThickness: 0.45,
    color: "#6f9f96",
    previewMaterialLabel: "450mm"
  },
  {
    id: "test-wall-fire-rated",
    categoryId: "wall-tool",
    label: "방화벽",
    shape: "wall-line",
    placementMode: "draw-wall",
    drawMode: "chain-wall",
    supportKind: "wall",
    size: [1, 2.7, 0.24],
    wallHeight: 2.7,
    wallThickness: 0.24,
    color: "#b4ada4",
    previewMaterialLabel: "fire"
  },
  {
    id: "test-wall-insulated",
    categoryId: "wall-tool",
    label: "단열 외벽",
    shape: "wall-line",
    placementMode: "draw-wall",
    drawMode: "chain-wall",
    supportKind: "wall",
    size: [1, 2.7, 0.32],
    wallHeight: 2.7,
    wallThickness: 0.32,
    color: "#86a9a1",
    previewMaterialLabel: "insul"
  },
  {
    id: "test-wall-low-900",
    categoryId: "wall-tool",
    label: "낮은 벽 900",
    shape: "wall-line",
    placementMode: "draw-wall",
    drawMode: "chain-wall",
    supportKind: "wall",
    size: [1, 0.9, 0.16],
    wallHeight: 0.9,
    wallThickness: 0.16,
    color: "#a7c7bd",
    previewMaterialLabel: "low"
  },
  {
    id: "test-wall-parapet",
    categoryId: "wall-tool",
    label: "파라펫 벽",
    shape: "wall-line",
    placementMode: "draw-wall",
    drawMode: "chain-wall",
    supportKind: "wall",
    size: [1, 1.05, 0.22],
    wallHeight: 1.05,
    wallThickness: 0.22,
    color: "#93b8ae",
    previewMaterialLabel: "parapet"
  },
  {
    id: "test-wall-concrete-core",
    categoryId: "wall-tool",
    label: "콘크리트 구조벽",
    shape: "wall-line",
    placementMode: "draw-wall",
    drawMode: "chain-wall",
    supportKind: "wall",
    size: [1, 2.7, 0.35],
    wallHeight: 2.7,
    wallThickness: 0.35,
    color: "#8c9894",
    previewMaterialLabel: "core"
  },
  {
    id: "test-wall-retaining",
    categoryId: "wall-tool",
    label: "옹벽",
    shape: "wall-line",
    placementMode: "draw-wall",
    drawMode: "chain-wall",
    supportKind: "wall",
    size: [1, 1.8, 0.4],
    wallHeight: 1.8,
    wallThickness: 0.4,
    color: "#7f8a87",
    previewMaterialLabel: "retain"
  },
  {
    id: "test-wall-precast-panel",
    categoryId: "wall-tool",
    label: "프리캐스트 패널",
    shape: "wall-line",
    placementMode: "draw-wall",
    drawMode: "chain-wall",
    supportKind: "wall",
    size: [1, 2.7, 0.18],
    wallHeight: 2.7,
    wallThickness: 0.18,
    color: "#a0aaa5",
    previewMaterialLabel: "pc"
  },
  {
    id: "test-wall-glass",
    categoryId: "wall-tool",
    label: "유리 벽",
    shape: "wall-line",
    placementMode: "draw-wall",
    drawMode: "chain-wall",
    supportKind: "wall",
    size: [1, 2.7, 0.12],
    wallHeight: 2.7,
    wallThickness: 0.12,
    color: "#83bdd0",
    previewMaterialLabel: "glass"
  },
  {
    id: "test-wall-slatted-screen",
    categoryId: "wall-tool",
    label: "루버 스크린 벽",
    shape: "wall-line",
    placementMode: "draw-wall",
    drawMode: "chain-wall",
    supportKind: "wall",
    size: [1, 2.4, 0.12],
    wallHeight: 2.4,
    wallThickness: 0.12,
    color: "#b19a7f",
    previewMaterialLabel: "louver"
  },
  {
    id: "test-wall-curved",
    categoryId: "wall-tool",
    label: "곡면 벽",
    shape: "curved-wall",
    placementMode: "draw-wall",
    drawMode: "arc-wall",
    supportKind: "wall",
    size: [1, 2.7, 0.18],
    wallHeight: 2.7,
    wallThickness: 0.18,
    color: "#87b8ad",
    previewMaterialLabel: "curve",
    previewQuality: "planned",
    status: "coming-soon",
    disabledReason: "곡면 벽 생성 엔진 연동 예정"
  },
  { id: "test-basement", categoryId: "wall-tool", label: "지하실 블록", shape: "box", placementMode: "floor-structural", supportKind: "wall", size: [1, 2.7, 1], color: "#9da8a1" },
  {
    id: "test-door-01",
    categoryId: "door",
    label: "현관문",
    shape: "door",
    placementMode: "wall-opening",
    openingType: "door",
    openingSize: [0.9, 2.1],
    defaultSillHeight: 0,
    frameDepth: 0.16,
    size: [1, 2.1, 0.2],
    color: "#8c5d3c"
  },
  {
    id: "test-door-02",
    categoryId: "door",
    label: "유리문",
    shape: "door",
    placementMode: "wall-opening",
    openingType: "door",
    openingSize: [1, 2.1],
    defaultSillHeight: 0,
    frameDepth: 0.16,
    size: [1, 2.1, 0.2],
    color: "#7aa1ad"
  },
  {
    id: "test-door-sliding-glass",
    categoryId: "door",
    label: "슬라이딩 유리문",
    shape: "door",
    placementMode: "wall-opening",
    openingType: "door",
    openingSize: [1.8, 2.1],
    defaultSillHeight: 0,
    frameDepth: 0.16,
    size: [1.8, 2.1, 0.2],
    color: "#7fa9b6",
    previewMaterialLabel: "slider"
  },
  {
    id: "test-door-wood-narrow",
    categoryId: "door",
    label: "협폭 목문",
    shape: "door",
    placementMode: "wall-opening",
    openingType: "door",
    openingSize: [0.75, 2],
    defaultSillHeight: 0,
    frameDepth: 0.16,
    size: [0.75, 2, 0.2],
    color: "#9a6b47",
    previewMaterialLabel: "wood"
  },
  {
    id: "test-window-01",
    categoryId: "window",
    label: "정방형 창",
    shape: "window",
    placementMode: "wall-opening",
    openingType: "window",
    openingSize: [1, 1],
    defaultSillHeight: 0.9,
    frameDepth: 0.18,
    size: [1, 1, 0.2],
    color: "#7eb4c0"
  },
  {
    id: "test-window-wide",
    categoryId: "window",
    label: "와이드 창",
    shape: "window-wide",
    placementMode: "wall-opening",
    openingType: "window",
    openingSize: [2, 1],
    defaultSillHeight: 0.9,
    frameDepth: 0.18,
    size: [2, 1, 0.2],
    color: "#77aabd"
  },
  {
    id: "test-window-slim-vertical",
    categoryId: "window",
    label: "세로 슬림 창",
    shape: "window",
    placementMode: "wall-opening",
    openingType: "window",
    openingSize: [0.55, 1.45],
    defaultSillHeight: 0.65,
    frameDepth: 0.18,
    size: [0.55, 1.45, 0.2],
    color: "#86bfd1",
    previewMaterialLabel: "slim"
  },
  {
    id: "test-window-ribbon",
    categoryId: "window",
    label: "리본 창",
    shape: "window-wide",
    placementMode: "wall-opening",
    openingType: "window",
    openingSize: [2.4, 0.55],
    defaultSillHeight: 1.35,
    frameDepth: 0.18,
    size: [2.4, 0.55, 0.2],
    color: "#6ea8bb",
    previewMaterialLabel: "ribbon"
  },
  {
    id: "test-window-picture",
    categoryId: "window",
    label: "픽처 창",
    shape: "window-wide",
    placementMode: "wall-opening",
    openingType: "window",
    openingSize: [1.6, 1.35],
    defaultSillHeight: 0.65,
    frameDepth: 0.18,
    size: [1.6, 1.35, 0.2],
    color: "#8cc7d5",
    previewMaterialLabel: "picture"
  },
  {
    id: "test-wall-pattern-brick",
    categoryId: "wall-pattern",
    label: "벽돌 패턴",
    shape: "tile",
    placementMode: "wall-attached",
    attachmentSize: [1.6, 1.2],
    attachDepth: 0.05,
    size: [1, 0.18, 1],
    color: "#bd8b72"
  },
  {
    id: "test-wall-pattern-stucco",
    categoryId: "wall-pattern",
    label: "스타코 패턴",
    shape: "tile",
    placementMode: "wall-attached",
    attachmentSize: [1.6, 1.2],
    attachDepth: 0.05,
    size: [1, 0.18, 1],
    color: "#e4dfcf"
  },
  {
    id: "test-wall-pattern-stone",
    categoryId: "wall-pattern",
    label: "석재 패턴",
    shape: "tile",
    placementMode: "wall-attached",
    attachmentSize: [1.8, 1.2],
    attachDepth: 0.06,
    size: [1, 0.18, 1],
    color: "#9f9483",
    previewMaterialLabel: "stone"
  },
  {
    id: "test-wall-pattern-wood-siding",
    categoryId: "wall-pattern",
    label: "우드 사이딩",
    shape: "tile",
    placementMode: "wall-attached",
    attachmentSize: [1.8, 1.2],
    attachDepth: 0.05,
    size: [1, 0.18, 1],
    color: "#b4875f",
    previewMaterialLabel: "siding"
  },
  {
    id: "test-wall-pattern-panel",
    categoryId: "wall-pattern",
    label: "세로 패널",
    shape: "tile",
    placementMode: "wall-attached",
    attachmentSize: [1.2, 1.8],
    attachDepth: 0.05,
    size: [1, 0.18, 1],
    color: "#d7d0be",
    previewMaterialLabel: "panel"
  },
  {
    id: "test-spandrel-01",
    categoryId: "spandrel",
    label: "스팬드럴",
    shape: "beam",
    placementMode: "wall-attached",
    attachmentSize: [2, 0.28],
    attachDepth: 0.1,
    size: [2, 0.28, 0.25],
    color: "#f0efe8"
  },
  {
    id: "test-spandrel-wood",
    categoryId: "spandrel",
    label: "목재 스팬드럴",
    shape: "beam",
    placementMode: "wall-attached",
    attachmentSize: [2.2, 0.32],
    attachDepth: 0.1,
    size: [2.2, 0.32, 0.22],
    color: "#a57755",
    previewMaterialLabel: "wood"
  },
  {
    id: "test-spandrel-metal",
    categoryId: "spandrel",
    label: "메탈 스팬드럴",
    shape: "beam",
    placementMode: "wall-attached",
    attachmentSize: [2.2, 0.24],
    attachDepth: 0.08,
    size: [2.2, 0.24, 0.18],
    color: "#8f989c",
    previewMaterialLabel: "metal"
  },
  {
    id: "test-column-01",
    categoryId: "column",
    label: "사각 기둥",
    shape: "column",
    placementMode: "floor-structural",
    supportKind: "column",
    size: [0.5, 2.7, 0.5],
    color: "#d7d1c1"
  },
  {
    id: "test-column-round",
    categoryId: "column",
    label: "원형 기둥",
    shape: "column",
    placementMode: "floor-structural",
    supportKind: "column",
    size: [0.42, 2.7, 0.42],
    color: "#d8d4c5",
    previewMaterialLabel: "round"
  },
  {
    id: "test-column-slim-steel",
    categoryId: "column",
    label: "슬림 철골 기둥",
    shape: "column",
    placementMode: "floor-structural",
    supportKind: "column",
    size: [0.28, 2.7, 0.28],
    color: "#9da7a8",
    previewMaterialLabel: "steel"
  },
  { id: "test-gate-01", categoryId: "gate", label: "게이트", shape: "gate", placementMode: "floor-free", size: [2, 1, 0.25], color: "#766657" },
  { id: "test-gate-driveway", categoryId: "gate", label: "차량 게이트", shape: "gate", placementMode: "floor-free", size: [3.2, 1.35, 0.25], color: "#6f6256", previewMaterialLabel: "driveway" },
  { id: "test-gate-pedestrian", categoryId: "gate", label: "보행자 게이트", shape: "gate", placementMode: "floor-free", size: [1.05, 1.25, 0.22], color: "#857566", previewMaterialLabel: "walk" },
  {
    id: "test-stairs-straight",
    categoryId: "stairs-ladder",
    label: "직선 계단",
    shape: "stairs",
    placementMode: "floor-stair",
    stairType: "straight",
    stairRise: 0.18,
    stairRun: 0.28,
    stepCount: 10,
    stair: {
      kind: "stair",
      layout: "straight",
      orientation: { ascentDirection: "south" },
      railingAttachments: [
        { assetId: "test-railing-01", id: "straight-railing-left", relation: "stair-railing", side: "left", segment: "full" },
        { assetId: "test-railing-01", id: "straight-railing-right", relation: "stair-railing", side: "right", segment: "full" }
      ]
    },
    size: [1.2, 1.8, 2.8],
    color: "#b7bab0"
  },
  {
    id: "test-stairs-wide",
    categoryId: "stairs-ladder",
    label: "와이드 계단",
    shape: "stairs",
    placementMode: "floor-stair",
    stairType: "straight",
    stairRise: 0.16,
    stairRun: 0.3,
    stepCount: 8,
    landingDepth: 0.55,
    stair: {
      kind: "stair",
      layout: "landing",
      orientation: { ascentDirection: "south" },
      railingAttachments: [
        { assetId: "test-railing-01", id: "wide-railing-left", relation: "stair-railing", side: "left", segment: "full" },
        { assetId: "test-railing-01", id: "wide-railing-right", relation: "stair-railing", side: "right", segment: "full" }
      ]
    },
    size: [1.8, 1.28, 2.95],
    color: "#c3c2b9"
  },
  {
    id: "test-stairs-landing",
    categoryId: "stairs-ladder",
    label: "참 계단",
    shape: "stairs",
    placementMode: "floor-stair",
    stairType: "landing",
    stairRise: 0.17,
    stairRun: 0.27,
    stepCount: 12,
    landingDepth: 0.75,
    stair: {
      kind: "stair",
      layout: "landing",
      orientation: { ascentDirection: "south" },
      railingAttachments: [
        { assetId: "test-railing-01", id: "landing-railing-left", relation: "stair-railing", side: "left", segment: "run" },
        { assetId: "test-railing-01", id: "landing-railing-right", relation: "stair-railing", side: "right", segment: "run" }
      ]
    },
    size: [1.35, 2.04, 3.99],
    color: "#b9b7aa"
  },
  {
    id: "test-stairs-porch",
    categoryId: "stairs-ladder",
    label: "현관/포치 계단",
    shape: "stairs",
    placementMode: "floor-stair",
    stairType: "landing",
    stairRise: 0.15,
    stairRun: 0.32,
    stepCount: 4,
    landingDepth: 0.45,
    stair: {
      kind: "stair",
      landingDepth: 0.45,
      layout: "landing",
      orientation: { ascentDirection: "south" },
      railingAttachments: [
        { assetId: "test-railing-01", id: "porch-railing-left", relation: "stair-railing", side: "left", segment: "full" },
        { assetId: "test-railing-01", id: "porch-railing-right", relation: "stair-railing", side: "right", segment: "full" }
      ],
      stepCount: 4
    },
    size: [1.5, 0.6, 1.73],
    color: "#d0c3ad",
    previewMaterialLabel: "porch"
  },
  {
    id: "test-stairs-deck",
    categoryId: "stairs-ladder",
    label: "옥외 데크 계단",
    shape: "stairs",
    placementMode: "floor-stair",
    stairType: "landing",
    stairRise: 0.17,
    stairRun: 0.3,
    stepCount: 6,
    landingDepth: 0.6,
    stair: {
      kind: "stair",
      landingDepth: 0.6,
      layout: "landing",
      orientation: { ascentDirection: "south" },
      railingAttachments: [
        { assetId: "test-railing-01", id: "deck-railing-left", relation: "stair-railing", side: "left", segment: "full" },
        { assetId: "test-railing-01", id: "deck-railing-right", relation: "stair-railing", side: "right", segment: "full" }
      ],
      stepCount: 6
    },
    size: [1.35, 1.02, 2.4],
    color: "#b89772",
    previewMaterialLabel: "deck"
  },
  {
    id: "test-stairs-service-compact",
    categoryId: "stairs-ladder",
    label: "콤팩트 서비스 계단",
    shape: "stairs",
    placementMode: "floor-stair",
    stairType: "straight",
    stairRise: 0.2,
    stairRun: 0.24,
    stepCount: 7,
    landingDepth: 0,
    stair: {
      kind: "stair",
      landingDepth: 0,
      layout: "straight",
      orientation: { ascentDirection: "south" },
      railingAttachments: [
        { assetId: "test-railing-01", id: "service-compact-railing-right", relation: "stair-railing", side: "right", segment: "full" }
      ],
      stepCount: 7
    },
    size: [0.9, 1.4, 1.68],
    color: "#aeb3aa",
    previewMaterialLabel: "service"
  },
  {
    id: "test-ladder-01",
    categoryId: "stairs-ladder",
    label: "외부 사다리",
    shape: "ladder",
    placementMode: "floor-stair",
    stairType: "ladder",
    stairRise: 0.32,
    stairRun: 0.08,
    stepCount: 8,
    stair: {
      kind: "ladder",
      layout: "ladder",
      orientation: { ascentDirection: "south" }
    },
    size: [0.7, 2.56, 0.35],
    color: "#8f9a93"
  },
  {
    id: "test-railing-01",
    categoryId: "railing",
    label: "난간",
    shape: "railing",
    attachmentKind: "stair-railing",
    attachmentTarget: "stair",
    size: [2, 0.55, 0.2],
    color: "#8c9591"
  },
  {
    id: "test-railing-glass",
    categoryId: "railing",
    label: "유리 난간",
    shape: "railing",
    placementMode: "floor-free",
    attachmentKind: "stair-railing",
    attachmentTarget: "stair",
    size: [2, 0.7, 0.12],
    color: "#9fc7d2",
    previewMaterialLabel: "glass"
  },
  {
    id: "test-railing-wood",
    categoryId: "railing",
    label: "목재 난간",
    shape: "railing",
    placementMode: "floor-free",
    attachmentKind: "stair-railing",
    attachmentTarget: "stair",
    size: [2, 0.65, 0.18],
    color: "#a57c55",
    previewMaterialLabel: "wood"
  },
  {
    id: "test-railing-metal-slim",
    categoryId: "railing",
    label: "슬림 메탈 난간",
    shape: "railing",
    placementMode: "floor-free",
    attachmentKind: "stair-railing",
    attachmentTarget: "stair",
    size: [2, 0.62, 0.12],
    color: "#7f8b8d",
    previewMaterialLabel: "metal"
  }
];

export const STUDIO_CATALOG_HOME_ICON = Home;

export function getCatalogAssetsByCategory(categoryId) {
  return STUDIO_CATALOG_ASSETS.filter((asset) => asset.categoryId === categoryId);
}

export function getCatalogAsset(assetId) {
  return STUDIO_CATALOG_ASSETS.find((asset) => asset.id === assetId) ?? STUDIO_CATALOG_ASSETS[0];
}
